version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit
    container_name: gerrit
    ports:
      - 8081:8080
      - 29418:29418
    environment:
      - WEBURL=http://localhost:8081
    volumes:
      - gerrit_site:/var/gerrit/review_site

volumes:
  gerrit_site:

